# Generated by Django 5.1 on 2024-08-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('timeToCreate', models.DateField()),
                ('timeToResolve', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
